{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bca2a27-9d8e-4bf4-8fa9-ac568c935343",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "#Note: Here Exception class refers to the base class for all the exceptions.\n",
    "When creating a custom exception in Python, it is recommended to inherit from the built-in Exception class or one of its subclasses.\n",
    "Here are the reasons why using the Exception class is preferred:\n",
    "Standardization: Inheriting from Exception or its subclasses helps maintain consistency and adheres to the established Python exception hierarchy.\n",
    "This hierarchy allows for organized exception handling and clear understanding of exception types.\n",
    "Exception Handling: Python provides a powerful exception handling mechanism that allows you to catch and handle exceptions in a structured way.\n",
    "By inheriting from Exception, the custom exception will be compatible with the existing exception handling infrastructure. \n",
    "so we can catch your custom exception using a specific except block or handle it along with other exceptions in a more general manner.\n",
    "Robustness: The Exception class provides essential functionality that is often needed when dealing with exceptions. \n",
    "It includes attributes like args (arguments passed to the exception), message (the exception message), \n",
    "and methods like __str__() (to generate a string representation of the exception). By inheriting from Exception, \n",
    "the custom exception will inherit these capabilities, making it more robust and easier to work with."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bbe2c1cb-50a1-4171-abec-242238a63e93",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q2. Write a python program to print Python Exception Hierarchy.\n",
    "def print_all_exception_hierarchy():\n",
    "    exceptions = [BaseException]\n",
    "   \n",
    "    while exceptions:\n",
    "        current_exception = exceptions.pop(0)\n",
    "        print(current_exception.__name__)\n",
    "        sub_exceptions = current_exception.__subclasses__()\n",
    "        exceptions.extend(sub_exceptions)\n",
    "\n",
    "print_all_exception_hierarchy()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c8aaf1ac-88ba-41c7-88ca-2901943788d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "he ArithmeticError class in Python is a base class for exceptions related to arithmetic operations. \n",
    "It provides a common superclass for arithmetic-related exceptions, allowing catch blocks to handle these exceptions in a more general manner. \n",
    "Two specific exceptions derived from the ArithmeticError class are ZeroDivisionError and ValueError.\n",
    "\n",
    "-------------------------------ZeroDivisionError example----------------------------------------------------------------------\n",
    "try:\n",
    "    a = 2/0\n",
    "    print(a)\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "\n",
    "output: \n",
    "exception in code division by zero\n",
    "I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n",
    "\n",
    "-----------------ValueError example-------------------------------------------------------------------------------------------\n",
    "try:\n",
    "    a = int(\"ab\")\n",
    "    print(a)\n",
    "except ValueError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "\n",
    "output:\n",
    "         exception in code invalid literal for int() with base 10: 'ab'\n",
    "         I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01cdc61a-f102-4f9c-9416-dd893a7a2244",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "The LookupError class in Python is a base class for exceptions that occur when a key or index used to look up a value in a \n",
    "mapping or sequence is not found. It serves as a superclass for several specific lookup-related exceptions, \n",
    "providing a consistent way to handle lookup failures.\n",
    "\n",
    "The LookupError class is useful because it allows you to catch and handle lookup-related exceptions in a more general manner, \n",
    "without needing to handle each specific exception separately. By catching LookupError, you can handle any exception \n",
    "that is a subclass of LookupError, which includes the specific lookup-related exceptions defined in Python.\n",
    "\n",
    "-------KeyError--------------\n",
    "\n",
    "#Exception\n",
    "try:\n",
    "    dicr1 = {\"name\":\"supriyo\", \"age\": 21}\n",
    "    print(dicr1[\"name\"])\n",
    "    print(dicr1[\"gender\"])\n",
    "except KeyError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "\n",
    "output:\n",
    "    supriyo\n",
    "    exception in code 'gender'\n",
    "    I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n",
    "\n",
    "\n",
    "-------Indexerror--------------\n",
    "\n",
    "try:\n",
    "    list1=[1,2,3,4]\n",
    "    print(list1[10])\n",
    "except IndexError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "\n",
    "output:\n",
    "exception in code list index out of range\n",
    "I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9eadd14c-296e-42e7-a1bf-b5eccf529ac8",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "ImportError error generally occurs when we want to import a class that does not exist\n",
    "try:\n",
    "    import test1\n",
    "except ImportError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "output\n",
    "exception in code No module named 'test1'\n",
    "I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n",
    "\n",
    "\n",
    "The ModuleNotFoundError is an exception in Python that is raised when an imported module or package cannot be found or does not exist.\n",
    "\n",
    "\n",
    "try:\n",
    "    from mypackage import mymodule\n",
    "except ImportError as e:\n",
    "    print(\"exception in code\",e)\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"exception in code\",e)\n",
    "else:\n",
    "    print(\"Hurray try block executed without any exception!!!!\")\n",
    "finally:\n",
    "    print(\"I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\")\n",
    "\n",
    "output \n",
    "exception in code No module named 'mypackage'\n",
    "I don't care , mai rookne nahi wala,bhar mai jay duniya and exception, mai chalunga always\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c1e8d92-b155-402a-b03f-533e9d39e0ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "1> Use specific exceptions instead of using the Exception super class directly\n",
    "2> print always a valid message\n",
    "3> always try to log\n",
    "4> always avoid to write multiple unwanted exceptions\n",
    "5> always prepare a documentation\n",
    "6> clean up all the resources\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
